name: Build

on: [workflow_dispatch]

jobs:
  build:
    name: Build libs

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04, ubuntu-24.04-arm]
        include:
        - os: windows-latest
          resources-dir: windows-x64
        - os: ubuntu-22.04
          resources-dir: linux-x64
        - os: ubuntu-24.04-arm
          resources-dir: linux-arm64

    steps:
    - uses: actions/checkout@v5

    - uses: dtolnay/rust-toolchain@stable

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.1-dev

    - run: cargo update && cargo build --release

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: libs-${{ matrix.resources-dir }}
        path: |
          target/release/libpano_native_components.so
          target/release/libnative_webview.so
          target/release/pano_native_components.dll
          target/release/native_webview.dll